AWSTemplateFormatVersion: 2010-09-09
Description: AWS CloudFormation Template to create resources for ETL pipline.
Resources:
  S3BucketStaging:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: staging-area-bucket
      AccessControl: Private
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
    DeletionPolicy: Retain
  
  Indexer:
    Type: AWS::Lambda::Function
    Properties:
      Description: Build file index to upload files from FTP server
      FunctionName: indexer-v-0-0-1
      Code: 
        ImageUri: 307660119800.dkr.ecr.eu-central-1.amazonaws.com/indexer:latest
      MemorySize: 512
      PackageType: Image
      Role: !GetAtt 'IndexerRole.Arn'
      Timeout: 900

  IndexerRole:      
    Type: AWS::IAM::Role
    Properties: 
      AssumeRolePolicyDocument: 
        Version: "2012-10-17"
        Statement:
          Effect: Allow
          Principal:
            Service: 
             - lambda.amazonaws.com
          Action: 
              - 'sts:AssumeRole'
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/service-role/AmazonS3ObjectLambdaExecutionRolePolicy
      RoleName: IndexerRole

  EventRule0:
    Type: AWS::Events::Rule
    Properties:
      Description: Schedule for indexer aws lambda
      EventBusName: default
      Name: indexer-schedule
      ScheduleExpression: rate(24 hours)
      State: ENABLED
      Targets:
        - Id: Id83555565-723e-46d3-b5b5-39af9f7b23c7
          Arn: arn:aws:lambda:eu-central-1:307660119800:function:indexer-v-0-0-1

Outputs:
  StagingBucketName:
    Value: !Ref S3BucketStaging
    Description: Name of the staging ares s3 bucket.



      