AWSTemplateFormatVersion: 2010-09-09
Description: AWS CloudFormation Template to create resources for ETL pipline.
Resources:
  S3BucketStaging:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: staging-area-bucket
      AccessControl: Private
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
    DeletionPolicy: Retain
  
  Indexer:
    Type: AWS::Lambda::Function
    Properties:
      Description: Build file index to upload files from FTP server
      FunctionName: indexer-v-0-0-1
      Code: 
        ImageUri: 307660119800.dkr.ecr.eu-central-1.amazonaws.com/indexer:latest
      MemorySize: 512
      PackageType: Image
      Role: !GetAtt 'IndexerRole.Arn'
      Timeout: 600

  IndexerRole:      
    Type: AWS::IAM::Role
    Properties: 
      AssumeRolePolicyDocument: 
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: 
              - lambda.amazonaws.com
            Action: 
              - 'sts:AssumeRole'
      Path: /
      Policies:
        - PolicyName: S3write
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Sid: "ListObjectsInBucket"
                Effect: Allow
                Action: 
                  - 's3:ListBucket'
                Resource: 
                  - 'arn:aws:s3:::staging-area-bucket'
              - Sid: "AllObjectActions"
                Effect: Allow
                Action: 
                  - 's3:*Object'
                Resource: 
                  - 'arn:aws:s3:::staging-area-bucket/*'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      RoleName: IndexerRole

  EventRule0:
    Type: AWS::Events::Rule
    Properties:
      EventBusName: default
      Name: indexer-schedule
      ScheduleExpression: rate(24 hours)
      State: ENABLED
      Targets:
        - Id: Id83555565-723e-46d3-b5b5-39af9f7b23c7
          Arn: arn:aws:lambda:eu-central-1:307660119800:function:indexer-v-0-0-1

  # Dynamo DB index table
  folders:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      KeySchema:
        - AttributeName: folder
          KeyType: HASH
      AttributeDefinitions:
        - AttributeName: folder
          AttributeType: S
      GlobalSecondaryIndexes: []
      BillingMode: PROVISIONED
      TableName: folders
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
  TablefoldersReadCapacityScalableTarget:
    Type: 'AWS::ApplicationAutoScaling::ScalableTarget'
    DependsOn: folders
    Properties:
      ServiceNamespace: dynamodb
      ResourceId: table/folders
      ScalableDimension: 'dynamodb:table:ReadCapacityUnits'
      MinCapacity: 1
      MaxCapacity: 10
      RoleARN: !Sub >-
        arn:aws:iam::${AWS::AccountId}:role/aws-service-role/dynamodb.application-autoscaling.amazonaws.com/AWSServiceRoleForApplicationAutoScaling_DynamoDBTable
  TablefoldersReadCapacityScalingPolicy:
    Type: 'AWS::ApplicationAutoScaling::ScalingPolicy'
    DependsOn: TablefoldersReadCapacityScalableTarget
    Properties:
      ServiceNamespace: dynamodb
      ResourceId: table/folders
      ScalableDimension: 'dynamodb:table:ReadCapacityUnits'
      PolicyName: folders-read-capacity-scaling-policy
      PolicyType: TargetTrackingScaling
      TargetTrackingScalingPolicyConfiguration:
        PredefinedMetricSpecification:
          PredefinedMetricType: DynamoDBReadCapacityUtilization
        ScaleOutCooldown: 60
        ScaleInCooldown: 60
        TargetValue: 70
  TablefoldersWriteCapacityScalableTarget:
    Type: 'AWS::ApplicationAutoScaling::ScalableTarget'
    DependsOn: folders
    Properties:
      ServiceNamespace: dynamodb
      ResourceId: table/folders
      ScalableDimension: 'dynamodb:table:WriteCapacityUnits'
      MinCapacity: 1
      MaxCapacity: 10
      RoleARN: !Sub >-
        arn:aws:iam::${AWS::AccountId}:role/aws-service-role/dynamodb.application-autoscaling.amazonaws.com/AWSServiceRoleForApplicationAutoScaling_DynamoDBTable
  TablefoldersWriteCapacityScalingPolicy:
    Type: 'AWS::ApplicationAutoScaling::ScalingPolicy'
    DependsOn: TablefoldersWriteCapacityScalableTarget
    Properties:
      ServiceNamespace: dynamodb
      ResourceId: table/folders
      ScalableDimension: 'dynamodb:table:WriteCapacityUnits'
      PolicyName: folders-write-capacity-scaling-policy
      PolicyType: TargetTrackingScaling
      TargetTrackingScalingPolicyConfiguration:
        PredefinedMetricSpecification:
          PredefinedMetricType: DynamoDBWriteCapacityUtilization
        ScaleOutCooldown: 60
        ScaleInCooldown: 60
        TargetValue: 70
  files:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      KeySchema:
        - AttributeName: filename
          KeyType: HASH
      AttributeDefinitions:
        - AttributeName: filename
          AttributeType: S
        - AttributeName: folder
          AttributeType: S
      GlobalSecondaryIndexes:
        - IndexName: folder_index
          KeySchema:
            - AttributeName: folder
              KeyType: HASH
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1
      BillingMode: PROVISIONED
      TableName: files
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
    DependsOn: folders
  TablefilesReadCapacityScalableTarget:
    Type: 'AWS::ApplicationAutoScaling::ScalableTarget'
    DependsOn: files
    Properties:
      ServiceNamespace: dynamodb
      ResourceId: table/files
      ScalableDimension: 'dynamodb:table:ReadCapacityUnits'
      MinCapacity: 1
      MaxCapacity: 10
      RoleARN: !Sub >-
        arn:aws:iam::${AWS::AccountId}:role/aws-service-role/dynamodb.application-autoscaling.amazonaws.com/AWSServiceRoleForApplicationAutoScaling_DynamoDBTable
  TablefilesReadCapacityScalingPolicy:
    Type: 'AWS::ApplicationAutoScaling::ScalingPolicy'
    DependsOn: TablefilesReadCapacityScalableTarget
    Properties:
      ServiceNamespace: dynamodb
      ResourceId: table/files
      ScalableDimension: 'dynamodb:table:ReadCapacityUnits'
      PolicyName: files-read-capacity-scaling-policy
      PolicyType: TargetTrackingScaling
      TargetTrackingScalingPolicyConfiguration:
        PredefinedMetricSpecification:
          PredefinedMetricType: DynamoDBReadCapacityUtilization
        ScaleOutCooldown: 60
        ScaleInCooldown: 60
        TargetValue: 70
  TablefilesWriteCapacityScalableTarget:
    Type: 'AWS::ApplicationAutoScaling::ScalableTarget'
    DependsOn: files
    Properties:
      ServiceNamespace: dynamodb
      ResourceId: table/files
      ScalableDimension: 'dynamodb:table:WriteCapacityUnits'
      MinCapacity: 1
      MaxCapacity: 10
      RoleARN: !Sub >-
        arn:aws:iam::${AWS::AccountId}:role/aws-service-role/dynamodb.application-autoscaling.amazonaws.com/AWSServiceRoleForApplicationAutoScaling_DynamoDBTable
  TablefilesWriteCapacityScalingPolicy:
    Type: 'AWS::ApplicationAutoScaling::ScalingPolicy'
    DependsOn: TablefilesWriteCapacityScalableTarget
    Properties:
      ServiceNamespace: dynamodb
      ResourceId: table/files
      ScalableDimension: 'dynamodb:table:WriteCapacityUnits'
      PolicyName: files-write-capacity-scaling-policy
      PolicyType: TargetTrackingScaling
      TargetTrackingScalingPolicyConfiguration:
        PredefinedMetricSpecification:
          PredefinedMetricType: DynamoDBWriteCapacityUtilization
        ScaleOutCooldown: 60
        ScaleInCooldown: 60
        TargetValue: 70
  TablefilesIndexfolderIndexReadCapacityScalableTarget:
    Type: 'AWS::ApplicationAutoScaling::ScalableTarget'
    DependsOn: files
    Properties:
      ServiceNamespace: dynamodb
      ResourceId: table/files/index/folder_index
      ScalableDimension: 'dynamodb:index:ReadCapacityUnits'
      MinCapacity: 1
      MaxCapacity: 10
      RoleARN: !Sub >-
        arn:aws:iam::${AWS::AccountId}:role/aws-service-role/dynamodb.application-autoscaling.amazonaws.com/AWSServiceRoleForApplicationAutoScaling_DynamoDBTable
  TablefilesIndexfolderIndexReadCapacityScalingPolicy:
    Type: 'AWS::ApplicationAutoScaling::ScalingPolicy'
    DependsOn: TablefilesIndexfolderIndexReadCapacityScalableTarget
    Properties:
      ServiceNamespace: dynamodb
      ResourceId: table/files/index/folder_index
      ScalableDimension: 'dynamodb:index:ReadCapacityUnits'
      PolicyName: files-index-folder_index-read-capacity-scaling-policy
      PolicyType: TargetTrackingScaling
      TargetTrackingScalingPolicyConfiguration:
        PredefinedMetricSpecification:
          PredefinedMetricType: DynamoDBReadCapacityUtilization
        ScaleOutCooldown: 60
        ScaleInCooldown: 60
        TargetValue: 70
  TablefilesIndexfolderIndexWriteCapacityScalableTarget:
    Type: 'AWS::ApplicationAutoScaling::ScalableTarget'
    DependsOn: files
    Properties:
      ServiceNamespace: dynamodb
      ResourceId: table/files/index/folder_index
      ScalableDimension: 'dynamodb:index:WriteCapacityUnits'
      MinCapacity: 1
      MaxCapacity: 10
      RoleARN: !Sub >-
        arn:aws:iam::${AWS::AccountId}:role/aws-service-role/dynamodb.application-autoscaling.amazonaws.com/AWSServiceRoleForApplicationAutoScaling_DynamoDBTable
  TablefilesIndexfolderIndexWriteCapacityScalingPolicy:
    Type: 'AWS::ApplicationAutoScaling::ScalingPolicy'
    DependsOn: TablefilesIndexfolderIndexWriteCapacityScalableTarget
    Properties:
      ServiceNamespace: dynamodb
      ResourceId: table/files/index/folder_index
      ScalableDimension: 'dynamodb:index:WriteCapacityUnits'
      PolicyName: files-index-folder_index-write-capacity-scaling-policy
      PolicyType: TargetTrackingScaling
      TargetTrackingScalingPolicyConfiguration:
        PredefinedMetricSpecification:
          PredefinedMetricType: DynamoDBWriteCapacityUtilization
        ScaleOutCooldown: 60
        ScaleInCooldown: 60
        TargetValue: 70

Outputs:
  StagingBucketName:
    Value: !Ref S3BucketStaging
    Description: Name of the staging ares s3 bucket.



      