name: Transformation step data-processor AWS Lambda CD
run-name: Deploy data-processor lambda
on:
  push:
    branches:
      - main
    paths:
      - 'pipeline/transformation/process_data/**'
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ACCOUNT_ID: ${{ env.AWS_ACCOUNT_ID }}
      REGION: ${{ env.AWS_REGION }}
      ECR_REPOSITORY: data-processor
    
    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: $REGION
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        run: |
          docker build -t $ACCAUNT_ID.dkr.ecr.$REGION.amazonaws.com/$ECR_REPOSITORY:latest pipeline/transformation/process_data/
          docker push $ACCAUNT_ID.dkr.ecr.$REGION.amazonaws.com/$ECR_REPOSITORY:latest
      - name: Update AWS Lambda function
        id: update-function
        run: |
          aws lambda update-function-code --function-name data-processor --image-uri $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/$ECR_REPOSITORY:latest