name: Deploy ETL pipeline
on:
  workflow_dispatch:

jobs:
  
  DeployIndexer:
    uses: ./.github/workflows/indexer-cd.yaml

  DeployListFiles:
    uses: ./.github/workflows/list-files-cd.yaml

  DeployLoader:
    uses: ./.github/workflows/loader-cd.yaml

  DeployIndexMarker:
    uses: ./.github/workflows/index-marker-cd.yaml

  DeployLocationProcessor:
    uses: ./.github/workflows/location-processor-cd.yaml

  DeployDataProcessor:
    uses: ./.github/workflows/data-processor-cd.yaml

  DeployFileMover:
    uses: ./.github/workflows/file-mover-cd.yaml

  DeployDimensionLoader:
    uses: ./.github/workflows/dimension-loader-cd.yaml

  DeployFactLoader:
    uses: ./.github/workflows/fact-loader-cd.yaml
  
  DeployCloudFormation:
    uses: ./.github/workflows/deploy-cloudformation-stack.yaml

  CreateSchema:
    runs-on: ubuntu-latest
    needs: [DeployCloudFormation]
    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Create Aurora schema
        run: |
          bash ./scripts/create_schema.sh