name: list-files-cd
run-name: Deploy list-files lambda
on: 
  push:
    branches:
      - main
    paths:
      - 'pipeline/extraction/list_files/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ACCAUNT_ID: ${{ secrets.ACCOUNT_ID }}
          ECR_REPOSITORY: list-files
          IMAGE_TAG: latest
        run: |
          docker build -t $ACCAUNT_ID.dkr.ecr.eu-central-1.amazonaws.com/$ECR_REPOSITORY:$IMAGE_TAG pipeline/extraction/list_files/
          docker push $ACCAUNT_ID.dkr.ecr.eu-central-1.amazonaws.com/$ECR_REPOSITORY:latest
      - name: Update AWS Lambda function
        id: update-function
        env:
          ACCOUNT_ID: ${{ secrets.ACCOUNT_ID }}
          ECR_REPOSITORY: list-files
        run: |
          aws lambda update-function-code --image-uri $ACCOUNT_ID.dkr.ecr.eu-central-1.amazonaws.com/$ECR_REPOSITORY:latest