name: Extraction step list-files AWS Lambda CD
run-name: Deploy list-files lambda
on: 
  push:
    branches:
      - main
    paths:
      - 'pipeline/extraction/list_files/**'
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        run: |
          docker build -t ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/list-files:latest pipeline/extraction/list_files/
          docker push ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/list-files:latest
      - name: Update AWS Lambda function
        id: update-function
        run: |
          aws lambda update-function-code --function-name list-files --image-uri ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.$REGION.amazonaws.com/list-files:latest