name: Step Function CD
run-name: Deploy step function
on: 
  push:
    branches:
      - main
    paths:
      - 'aws/StepFunction.asl.json'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Replace account_id and region
        run: |
          sed -i "s/307660119800/${{ secrets.AWS_ACCOUNT_ID }}/g" aws/StepFunction.asl.json
          sed -i "s/eu-central-1/${{ secrets.AWS_REGION }}/g" aws/StepFunction.asl.json
      - name: Update Step Function
        run: |
          aws stepfunctions update-state-machine --state-machine-arn arn:aws:states:${{ secrets.AWS_REGION }}:${{ secrets.AWS_ACCOUNT_ID }}:stateMachine:ETLStepFunction --definition file://aws/StepFunction.asl.json